### ISSUE TITLE
"Unrecognized field" exception when describing Lead

### ISSUE THREAD

**Issue by pavelpetrof** [palominolabs/sf-api-connector#6]
I get this exception when I call RestConnectionImpl.describeSObject(). This is similar to https://github.com/palominolabs/sf-api-connector/issues/1, so may be it'll be a good idea to set up Jackson to ignore unknown fields.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "quickActions" (class com.palominolabs.crm.sf.rest.SObjectUrls), not marked as ignorable (11 known properties: , "rowTemplateUrlPath", "sobjectUrlPath", "layouts", "describeUrlPath", "describe", "passwordUtilities", "sobject", "rowTemplate", "uiEditTemplate", "uiNewRecord", "uiDetailTemplate" [truncated]])
 at [Source: java.io.StringReader@5ee4fafe; line: 1, column: 4729](through reference chain: com.palominolabs.crm.sf.rest.SObjectUrls["quickActions"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1180)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:412)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:977)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:276)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:347)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:977)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:276)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1216)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:830)
    at com.palominolabs.crm.sf.rest.RestConnectionImpl.describeSObject(RestConnectionImpl.java:137)

**Comment by marshallpierce** [comment]
Argh! I could have sworn I already _had_ configured Jackson to always ignore unknown fields. Thanks for the report; I'll fix this right away.

**Comment by pavelpetrof** [comment]
Thank you. This is how I've fixed it (locally), and it seems to work:

In the beginning of RestConnectionPoolImpl.java: 

```
private final ObjectMapper objectMapper = createObjectMapper();

private static ObjectMapper createObjectMapper() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    return mapper;
}
```

**Comment by marshallpierce** [comment]
Yep, that's pretty much what I'd already typed. :)

Do you have a short repro for this? If not that's ok, but I do like having a failing test before I call a fix done. I have a test that does describeSObject on every available object type, but it's passing for me. Perhaps  your SF instance has a changerolled out to it that hasn't made it to my test org yet.

**Comment by pavelpetrof** [comment]
Here's the json that I received from SF (I've stripped the fields and childRelationships):

{
    "activateable": false, 
    "childRelationships": [
    <...>
    ], 
    "createable": true, 
    "custom": false, 
    "customSetting": false, 
    "deletable": true, 
    "deprecatedAndHidden": false, 
    "feedEnabled": true, 
    "fields": [
    <...>
   ], 
    "replicateable": true, 
    "retrieveable": true, 
    "searchLayoutable": true, 
    "searchable": true, 
    "triggerable": true, 
    "undeletable": true, 
    "updateable": true, 
    "urls": {
        "describe": "/services/data/v28.0/sobjects/Lead/describe", 
        "layouts": "/services/data/v28.0/sobjects/Lead/describe/layouts", 
        "quickActions": "/services/data/v28.0/sobjects/Lead/quickActions", 
        "rowTemplate": "/services/data/v28.0/sobjects/Lead/{ID}", 
        "sobject": "/services/data/v28.0/sobjects/Lead", 
        "uiDetailTemplate": "https://na6.salesforce.com/{ID}", 
        "uiEditTemplate": "https://na6.salesforce.com/{ID}/e", 
        "uiNewRecord": "https://na6.salesforce.com/00Q/e"
    }
}

by the way, this new field "quickActions" appears only in API version 28 (there isn't one in 27).

**Comment by marshallpierce** [comment]
OK, thanks. I might not be able to get around to releasing 1.0.2 for a day or two but in the meantime I've pushed a slightly condensed version of your fix if you wish to use that snapshot.

**Comment by marshallpierce** [comment]
1.0.2 has been released. Feel free to close this issue when it shows up for you in maven central (should be by tomorrow morning).

**Comment by marshallpierce** [comment]
Feel free to re-open if 1.0.2 did not fix the issue.
